### ISSUE TITLE
use APIv4

### ISSUE THREAD

**Issue by mpadge** [jonocarroll/starryeyes#1]
Just a flag here, but APIv4 obviates all need to parse messy html. I'll sketch the first bits of [`stellar`](https://github.com/mpadge/stellar) and ping you when done. Parsing `graphql` is supremely easy with the [`ghql` package](https://github.com/ropensci/ghql) - see @maelle's [`ghrecipes`](https://github.com/ropenscilabs/ghrecipes) for some great examples.

**Comment by jonocarroll** [comment]
I've done absolutely 0 graphQL so I'm absolutely interested in knowing more! Thanks for the links.

starryeyes was an experimental project (notice: all the commits were in a single evening) so I'm happy to port over whatever bits are useful elsewhere. The chance to learn better practices elsewhere is very much a benefit to me.

For posterity: discussion of relevant overlap with prospective packages detailed here: https://github.com/mpadge/stellar/issues/1 soon to be moved to ropenscilabs.

**Comment by mpadge** [comment]
One more thought that fits best here for the moment, but updating `starryeyes` via APIv4 is totally easy because the `after` value of each user is a hashed global ID. These just need to be cached each time someone searches for a user, and the next run will then start only after the point at which it was last run and cached, returning only new stars since that point. Easy!
